apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uibx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-uibx@sha256:831ffd5901e11adbae90c2708133ab1eab6781ef2dddb3d5bb28561d935f075f
        name: my-nodejs
        resources: {}
status: {}
